# name: Release notes

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the main branch
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# # jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest

#     steps:
#       - name: Release changelog
#         uses: release-drafter/release-drafter@v5
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}